### ISSUE TITLE
Illuminate\Database\QueryException - Ao executar "php artisan migrate --seed"

### ISSUE THREAD

**Issue by maps75** [fsclaro/Vulcano#1]
Olá amigo.

Estou testando seu boilerplate e, ao executar o **_migrate_**, ocorre o erro na imagem em anexo.
Se puder verificar, agradeço!
Abraços.

![ERRO_Vulcano_Laravel](https://user-images.githubusercontent.com/9206512/59558318-50f59580-8fe7-11e9-9679-06774e7be245.png)

**Comment by fsclaro** [comment]
Olá amigo.

Testei aqui com o Windows 10 + Laragon 4.0.14 (Apache 2.4.25, MySQL 5.7.24, PHP 7.2.11) e não ocorreu o problema relatado.

Também testei com o Laragon utilizando o MariaDB 10.3.15 também sem erros.

Poderia me passar como está configurado o seu ambiente?

SO:
Apache:
PHP:
Database:

Fico à disposição

**Comment by maps75** [comment]
Ok. Agradeço.

**SO:** Windows 10 Pro 64bits
**Apache:** 2.4.37
**PHP:** 7.3.1
**Database:** MariaDB 10.1.37

Abçs.

**Comment by fsclaro** [comment]
Tente executar em 2 passos

php artisan migrate
php artisan db:seed

**Comment by flavioccf** [comment]
@maps75 acredito que seja a versão do seu DB, as colunas no formato JSON só funcionam corretamente a partir da versão 10.2.7 do MariaDB [https://mariadb.com/kb/en/library/json-data-type/](https://mariadb.com/kb/en/library/json-data-type/)

**Comment by maps75** [comment]
Obrigado @fsclaro e @flavioccf pela ajuda.
Alterei as colunas para "_text_" e funcionou.
Abraços.
